In [2]:
import pandas as pd
import numpy as np

In [3]:
loan_data_backup = pd.read_csv("loan.csv")

C:\JPMC\DEV\TMP\ds\data\tmp\ipykernel_26676\4198844725.py:1: DtypeWarning: Columns (19,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  loan_data_backup = pd.read_csv("loan.csv")

In [4]:
loan_data_backup.columns.to_list()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [126]:
loan_data = loan_data_backup.copy()

In [127]:
pd.options.display.max_columns = None

In [128]:
loan_data['emp_length'].unique()

array(['10+ years', '6 years', '4 years', '< 1 year', '2 years',
       '9 years', nan, '5 years', '3 years', '7 years', '1 year',
       '8 years'], dtype=object)

In [129]:
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('10+ years', '10')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', '0')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '')

In [132]:
loan_data['emp_length_int'].unique()

array([10.,  6.,  4.,  0.,  2.,  9., nan,  5.,  3.,  7.,  1.,  8.])

In [131]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])

In [133]:
loan_data["earliest_cr_line"]

0          Apr-01
1          Jun-87
2          Apr-11
3          Feb-06
4          Dec-00
            ...
1048570    Dec-83
1048571    Oct-81
1048572    Nov-85
1048573    Jun-06
1048574    Jan-95
Name: earliest_cr_line, Length: 1048575, dtype: object

In [134]:
loan_data["earliest_cr_date"] = pd.to_datetime(loan_data["earliest_cr_line"], format='%b-%y')

In [135]:
loan_data["earliest_cr_date"]

0         2001-04-01
1         1987-06-01
2         2011-04-01
3         2006-02-01
4         2000-12-01
             ...
1048570   1983-12-01
1048571   1981-10-01
1048572   1985-11-01
1048573   2006-06-01
1048574   1995-01-01
Name: earliest_cr_date, Length: 1048575, dtype: datetime64[ns]

In [136]:
loan_data['ref_date'] = pd.to_datetime('2017-12-01')

In [137]:
loan_data['mths_since_earliest_cr_line'] = (loan_data['ref_date'].dt.to_period('M') - loan_data['earliest_cr_date'].dt.to_period('M')).apply(lambda x: x.n)

In [138]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [139]:
loan_data['mths_since_earliest_cr_line'].describe()

count   1048575.00000
mean        201.79894
std          99.57988
min        -612.00000
25%         141.00000
50%         185.00000
75%         253.00000
max         587.00000
Name: mths_since_earliest_cr_line, dtype: float64

In [140]:
loan_data.loc[loan_data['mths_since_earliest_cr_line'] < 0, 'mths_since_earliest_cr_line'] = loan_data['mths_since_earliest_cr_line'].max()

In [141]:
loan_data['mths_since_earliest_cr_line'].describe()

count   1048575.00000
mean        204.18582
std          94.77147
min          25.00000
25%         141.00000
50%         186.00000
75%         254.00000
max         587.00000
Name: mths_since_earliest_cr_line, dtype: float64

In [142]:
loan_data['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [143]:
loan_data['term_int'] = loan_data['term'].str.replace(' months', '').str.strip()

In [145]:
loan_data['term_int'].unique()

array(['36', '60'], dtype=object)

In [146]:
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format='%b-%y')

In [147]:
loan_data['issue_d_date']

0         2018-12-01
1         2018-12-01
2         2018-12-01
3         2018-12-01
4         2018-12-01
             ...
1048570   2015-10-01
1048571   2015-10-01
1048572   2015-10-01
1048573   2015-10-01
1048574   2015-10-01
Name: issue_d_date, Length: 1048575, dtype: datetime64[ns]

In [148]:
loan_data['mths_since_issue_d'] = (loan_data['ref_date'].dt.to_period('M') - loan_data['issue_d_date'].dt.to_period('M')).apply(lambda x: x.n)

In [149]:
loan_data['issue_d_date'].unique()

<DatetimeArray>
['2018-12-01 00:00:00', '2018-11-01 00:00:00', '2018-10-01 00:00:00',
 '2018-09-01 00:00:00', '2018-08-01 00:00:00', '2018-07-01 00:00:00',
 '2018-06-01 00:00:00', '2018-05-01 00:00:00', '2018-04-01 00:00:00',
 '2018-03-01 00:00:00', '2018-02-01 00:00:00', '2018-01-01 00:00:00',
 '2016-09-01 00:00:00', '2016-08-01 00:00:00', '2016-07-01 00:00:00',
 '2016-06-01 00:00:00', '2016-05-01 00:00:00', '2016-04-01 00:00:00',
 '2016-03-01 00:00:00', '2016-02-01 00:00:00', '2016-01-01 00:00:00',
 '2016-12-01 00:00:00', '2016-11-01 00:00:00', '2016-10-01 00:00:00',
 '2015-12-01 00:00:00', '2015-11-01 00:00:00', '2015-10-01 00:00:00']
Length: 27, dtype: datetime64[ns]

In [151]:
loan_data.drop(loan_data[loan_data['issue_d_date'] > '2017-12-01'].index, inplace=True)

In [152]:
loan_data['mths_since_earliest_cr_line'].describe()

count   553333.00000
mean       219.90118
std         92.10159
min         49.00000
25%        157.00000
50%        201.00000
75%        267.00000
max        587.00000
Name: mths_since_earliest_cr_line, dtype: float64

In [153]:
loan_data_dummies = [
    pd.get_dummies(loan_data['grade'], prefix='grade', prefix_sep=':'),
    pd.get_dummies(loan_data['sub_grade'], prefix='sub_grade', prefix_sep=':'),
    pd.get_dummies(loan_data['home_ownership'], prefix='home_ownership', prefix_sep=':'),
    pd.get_dummies(loan_data['verification_status'], prefix='verification_status', prefix_sep=':'),
    pd.get_dummies(loan_data['loan_status'], prefix='loan_status', prefix_sep=':'),
    pd.get_dummies(loan_data['purpose'], prefix='purpose', prefix_sep=':'),
    pd.get_dummies(loan_data['addr_state'], prefix='addr_state', prefix_sep=':'),
    pd.get_dummies(loan_data['initial_list_status'], prefix='initial_list_status', prefix_sep=':'),
]

In [154]:
loan_data_dummies = pd.concat(loan_data_dummies, axis=1)

In [155]:
loan_data = pd.concat([loan_data, loan_data_dummies], axis=1)

In [156]:
loan_data

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,emp_length_int,earliest_cr_date,ref_date,mths_since_earliest_cr_line,term_int,issue_d_date,mths_since_issue_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:ND,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w
495242,NaN,NaN,8000,8000,8000.00000,36 months,12.79000,268.75000,C,C1,lead mold maker,4 years,MORTGAGE,95000.00000,Verified,Sep-16,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,600xx,IL,10.30000,0,May-93,1.00000,77.00000,79.00000,12,1,11343,47.90000,30,w,2063.66000,2063.66000,7521.68000,7521.68000,5936.34000,1585.34000,0.00000,0.00000,0.00000,Feb-19,268.75000,Mar-19,Feb-19,0,NaN,1,Individual,NaN,NaN,NaN,0,0,30705,2.00000,2.00000,2.00000,2.00000,2.00000,19362.00000,95.00000,5.00000,6.00000,3463.00000,70.00000,23700,5.00000,5.00000,17.00000,8,2559.00000,6558.00000,56.30000,0,0,120.00000,280,6,2,3,6.00000,NaN,1.00000,NaN,0,3,8,4,6,8,10,19.00000,8,12,0.00000,0,0,7,96.40000,75.00000,1,0,44176,30705,15000,20476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,4.00000,1993-05-01,2017-12-01,295,36,2016-09-01,15,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
495243,NaN,NaN,20000,20000,20000.00000,60 months,17.99000,507.76000,D,D2,Compliance Manager,1 year,MORTGAGE,66000.00000,Not Verified,Sep-16,Charged Off,n,NaN,NaN,medical,Medical expenses,786xx,TX,12.62000,2,Dec-08,0.00000,17.00000,117.00000,18,1,3565,31.00000,25,w,0.00000,0.00000,7366.25000,7366.25000,2711.49000,3341.65000,0.00000,1313.11000,236.35980,Oct-17,507.76000,NaN,Jul-18,0,45.00000,1,Individual,NaN,NaN,NaN,0,3841,235368,1.00000,11.00000,1.00000,2.00000,1.00000,26700.00000,101.00000,1.00000,1.00000,848.00000,80.00000,11500,1.00000,4.00000,2.00000,3,13076.00000,4891.00000,28.10000,0,0,91.00000,93,12,1,1,12.00000,NaN,12.00000,NaN,0,4,6,4,4,16,6,8.00000,6,18,0.00000,0,0,2,88.00000,25.00000,1,0,254093,30265,6800,26578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,2008-12-01,2017-12-01,108,60,2016-09-01,15,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True
495244,NaN,NaN,10000,10000,10000.00000,36 months,8.59000,316.10000,A,A5,Supervisory Agent,10+ years,MORTGAGE,137500.00000,Source Verified,Sep-16,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,330xx,FL,13.42000,0,May-02,1.00000,NaN,107.00000,18,1,9031,8.80000,37,w,0.00000,0.00000,10962.47908,10962.48000,10000.00000,962.48000,0.00000,0.00000,0.00000,Dec-18,35.67000,NaN,Dec-18,0,NaN,1,Individual,NaN,NaN,NaN,0,0,549316,0.00000,2.00000,2.00000,3.00000,9.00000,46469.00000,80.00000,0.00000,2.00000,8713.00000,18.00000,102800,4.00000,3.00000,3.00000,7,34332.00000,68269.00000,11.70000,0,0,143.00000,172,17,7,2,68.00000,NaN,2.00000,NaN,0,2,2,9,15,9,14,26.00000,2,18,0.00000,0,0,3,100.00000,0.00000,1,0,682041,55500,77300,72241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.00000,2002-05-01,2017-12-01,187,36,2016-09-01,15,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
495245,NaN,NaN,32200,32200,32200.00000,60 months,21.49000,880.02000,D,D5,warehouse/supervisor,10+ years,MORTGAGE,65000.00000,Not Verified,Sep-16,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,923xx,CA,11.71000,0,Nov-92,1.00000,NaN,87.00000,17,1,11987,48.10000,34,w,0.00000,0.00000,35770.81275,35770.81000,32200.00000,3570.81000,0.00000,0.00000,0.00000,Apr-17,31447.60000,NaN,Feb-19,0,NaN,1,Individual,NaN,NaN,NaN,0,0,173513,1.00000,2.00000,0.00000,3.00000,13.00000,12947.00000,82.00000,2.00000,2.00000,6087.00000,61.00000,24900,7.00000,0.00000,5.00000,5,10845.00000,2666.00000,80.80000,0,0,128.00000,286,3,3,3,32.00000,NaN,0.00000,NaN,0,3,5,5,10,7,14,24.00000,5,17,0.00000,0,0,2,100.00000,40.00000,1,0,199969,24934,13900,15886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.00000,1992-11-01,2017-12-01,301,60,2016-09-01,15,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
495246,NaN,NaN,2600,2600,2600.00000,36 months,8.99000,82.67000,B,B1,Loaner Coordinator,3 years,RENT,35000.00000,Source Verified,Sep-16,Fully Paid,n,NaN,NaN,moving,Moving and relocation,970xx,OR,6.73000,0,Sep-09,0.00000,NaN,NaN,14,0,720,1.40000,24,w,0.00000,0.00000,2662.59024,2662.59000,2600.00000,62.59000,0.00000,0.00000,0.00000,Jan-17,2492.06000,NaN,Dec-18,0,NaN,1,Individual,NaN,NaN,NaN,0,0,19497,0.00000,7.00000,0.00000,1.00000,13.00000,18777.00000,92.00000,0.00000,2.00000,383.00000,27.00000,52700,1.00000,0.00000,1.00000,3,1393.00000,49677.00000,1.00000,0,0,84.00000,61,13,13,0,24.00000,NaN,1.00000,NaN,0,4,5,6,8,14,7,10.00000,5,14,0.00000,0,0,0,100.00000,0.00000,0,0,73227,19497,50200,20527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,3.00000,2009-09-01,2017-12-01,99,36,2016-09-01,15,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaN,25000,25000,25000.00000,36 months,16.99000,891.20000,D,D3,Analyst,2 years,MORTGAGE,90000.00000,Not Verified,Oct-15,Fully Paid,n,NaN,NaN,other,Other,727xx,AR,17.48000,0,Dec-83,1.00000,NaN,46.00000,10,2,19491,77.70000,43,w,0.00000,0.00000,32059.31019,32059.31000,25000.00000,7059.31000,0.00000,0.00000,0.00000,Oct-18,890.91000,NaN,Feb-19,0,NaN,1,Individual,NaN,NaN,NaN,0,0,302557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25100,NaN,NaN,NaN,1,33617.00000,553.00000,92.80000,0,0,144.00000,381,27,9,7,101.00000,NaN,5.00000,NaN,0,2,7,3,10,8,8,28.00000,7,10,0.00000,0,0,1,100.00000,50.00000,0,2,337698,64487,7700,48369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,2.00000,1983-12-01,2017-12-01,408,36,2015-10-01,26,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1048571,NaN,NaN,24825,24825,24825.00000,36 months,16.55000,879.53000,D,D2,DENTIST,1 year,RENT,252000.00000,Source Verified,Oct-15,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,996xx,AK,19.59000,0,Oct-81,2.00000,29.00000,37.00000,14,3,2062,2.80000,30,w,0.00000,0.00000,31640.21312,31640.21000,24825.00000,6815.21000,0.00000,0.00000,0.00000,Oct-18,879.49000,NaN,Feb-19,0,47.00000,1,Individual,NaN,NaN,NaN,0,154,192443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46000,NaN,NaN,NaN,6,14803.00000,35802.00000,3.30000,0,0,304.00000,407,19,2,1,19.00000,NaN,1.00000,43.00000,1,2,3,4,5,20,6,9.00000,3,14,0.00000,0,0,5,82.60000,33.30000,0,3,292355,192443,37500,246355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,1981-10-01,2017-12-01,434,36,2015-10-01,26,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1048572,NaN,NaN,19650,19650,19650.00000,60 months,13.33000,450.43000,C,C3,Director,10+ years,OWN,95000.00000,Verified,Oct-15,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,146xx,NY,32.44000,0,Nov-85,0.00000,NaN,NaN,28,0,105783,29.80000,51,w,0.00000,0.00000,20569.17000,20569.17000,19650.00000,919.17000,0.00000,0.00000,0.00000,Feb-16,19232.43000,NaN,Jul-17,0,NaN,1,Individual,NaN,NaN,NaN,0,0,183091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,212400,NaN,NaN,NaN,10,7042.00000,77726.00000,35.50000,0,0,19.00000,358,6,4,2,6.00000,NaN,8.00000,NaN,0,6,9,15,23,2,26,47.00000,9,28,0.00000,0,0,3,100.00000,13.30000,0,0,297400,183091,120500,85000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.00000,1985-11-01,2017-12-01,385,60,2015-10-01,26,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1048573,NaN,NaN,31200,31200,31200.00000,60 months,19.99000,826.44000,E,E4,Certified Occupational Therapy Assistant,< 1 year,OWN,65000.00000,Source Verified,Oct-15,Current,n,NaN,NaN,home_improvement,Home improvement,296xx,SC,16.01000,0,Jun-06,1.00000,NaN,NaN,6,0,6399,50.40000,9,w,13959.27000,13959.27000,33158.69000,33158.69000,17240.73000,15917.96000,0.00000,0.00000,0.00000,Feb-19,826.44000,Mar-19,Feb-19,0,NaN,1,Individual,NaN,NaN,NaN,0,0,39135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12700,NaN,NaN,NaN,1,6523.00000,96.00000,97.80000,0,0,36.00000,111,29,24,0,29.00000,NaN,2.00000,NaN,0,2,4,2,3,2,4,7.00000,4,6,0.00000,0,0,0,100.00000,100.00000,0,0,55705,39135,4300,43005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,2006-06-01,2017-12-01,138,60,2015-10-01,26,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True

In [165]:
loan_data['emp_length_int'].isnull().sum()

35478

In [174]:
loan_data['mths_since_earliest_cr_line'].fillna(0, inplace=True)
loan_data['acc_now_delinq'].fillna(0, inplace=True)
loan_data['total_acc'].fillna(0, inplace=True)
loan_data['pub_rec'].fillna(0, inplace=True)
loan_data['open_acc'].fillna(0, inplace=True)
loan_data['inq_last_6mths'].fillna(0, inplace=True)
loan_data['delinq_2yrs'].fillna(0, inplace=True)
loan_data['emp_length_int'].fillna(0, inplace=True)

In [175]:
loan_data['emp_length_int'].isnull().sum()

0

In [176]:
loan_data['loan_status'].unique()

array(['Current', 'Charged Off', 'Fully Paid', 'Late (31-120 days)',
       'In Grace Period', 'Late (16-30 days)', 'Default'], dtype=object)

In [177]:
loan_data['loan_status'].value_counts()

loan_status
Fully Paid            291288
Current               165955
Charged Off            87344
Late (31-120 days)      5645
In Grace Period         2250
Late (16-30 days)        839
Default                   12
Name: count, dtype: int64

In [178]:
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off', 'Late (31-120 days)', 'Default']), 0 , 1)

In [180]:
loan_data[['good_bad', 'loan_status']]

         good_bad  loan_status
495242          1      Current
495243          0  Charged Off
495244          1   Fully Paid
495245          1   Fully Paid
495246          1   Fully Paid
...           ...          ...
1048570         1   Fully Paid
1048571         1   Fully Paid
1048572         1   Fully Paid
1048573         1      Current
1048574         1      Current

[553333 rows x 2 columns]