In [1]:
import pandas as pd
import numpy as np

In [2]:
loan_data_backup = pd.read_csv("loan.csv")

C:\Users\gui_k\AppData\Local\Temp\ipykernel_20408\4198844725.py:1: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  loan_data_backup = pd.read_csv("loan.csv")

In [3]:
loan_data_backup.columns.to_list()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [4]:
loan_data = loan_data_backup.copy()

In [5]:
pd.options.display.max_columns = None

In [6]:
loan_data.shape

(2260668, 145)

In [7]:
loan_data['emp_length'].unique()

array(['10+ years', '6 years', '4 years', '< 1 year', '2 years',
       '9 years', nan, '5 years', '3 years', '7 years', '1 year',
       '8 years'], dtype=object)

In [8]:
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('10+ years', '10')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', '0')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '')

In [9]:
loan_data['emp_length_int'].unique()

array(['10', '6', '4', '0', '2', '9', nan, '5', '3', '7', '1', '8'],
      dtype=object)

In [10]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])

In [11]:
loan_data["earliest_cr_line"].unique()

array(['Apr-2001', 'Jun-1987', 'Apr-2011', 'Feb-2006', 'Dec-2000',
       'Sep-2002', 'Nov-2004', 'Nov-1997', 'Aug-1998', 'Apr-2002',
       'May-2007', 'Dec-2003', 'Jun-2003', 'Oct-2008', 'Jul-1990',
       'Dec-1988', 'Dec-2002', 'Oct-2010', 'Jul-2005', 'Feb-2001',
       'Dec-2004', 'Oct-2001', 'Sep-2003', 'Oct-2004', 'Sep-2010',
       'Oct-1999', 'Feb-1997', 'Jan-1995', 'Aug-2005', 'Apr-2005',
       'Oct-2005', 'Nov-2006', 'Sep-1999', 'Sep-2006', 'Aug-1996',
       'May-2015', 'Nov-1999', 'Dec-1998', 'Aug-1989', 'Apr-2012',
       'Sep-2012', 'Jan-2011', 'Jul-2013', 'Sep-2011', 'Aug-1999',
       'Dec-1991', 'Nov-2007', 'Oct-2007', 'Jul-1986', 'Nov-2014',
       'Apr-1995', 'Jul-1992', 'Aug-2006', 'Oct-1988', 'Feb-2005',
       'Aug-2002', 'Oct-2003', 'Apr-2004', 'Jun-2007', 'Aug-1990',
       'Dec-1990', 'Jul-1997', 'Sep-1988', 'Sep-2008', 'Feb-1999',
       'Apr-2007', 'Aug-2004', 'Dec-2006', 'Mar-2007', 'Oct-2006',
       'Jul-2014', 'May-2005', 'Jun-1995', 'Mar-2014', 'Feb-2003',
       'Aug-2007', 'Jul-1996', 'Jan-1991', 'Aug-2008', 'Dec-2007',
       'Sep-1997', 'Jan-2000', 'Jan-2005', 'Feb-2007', 'Dec-2005',
       'Jan-2012', 'Dec-1997', 'Mar-2009', 'Apr-1989', 'Jun-2006',
       'Jan-2014', 'Jun-2009', 'May-1975', 'Apr-2014', 'Oct-1996',
       'Mar-1999', 'Dec-1994', 'Jan-2008', 'Jul-1999', 'Feb-2014',
       'Oct-2000', 'Aug-2010', 'Mar-1993', 'May-2009', 'Aug-1993',
       'May-1998', 'Sep-1998', 'Aug-2011', 'Nov-1984', 'Apr-2000',
       'Apr-2003', 'May-2003', 'Feb-1996', 'Jan-1996', 'Mar-2005',
       'Aug-2001', 'Oct-2011', 'Mar-1974', 'Jul-2007', 'Feb-1998',
       'Jan-2006', 'Mar-2006', 'Aug-2003', 'May-2004', 'Nov-2013',
       'Jan-2009', 'Jan-2002', 'Sep-1984', 'Jul-2010', 'Mar-1998',
       'Jun-1991', 'Sep-1996', 'Sep-1991', 'Mar-1991', 'Apr-1999',
       'Aug-2009', 'Nov-2001', 'Apr-2006', 'Dec-2009', 'Nov-1986',
       'Jan-2004', 'Nov-2002', 'Sep-1994', 'Mar-2000', 'Jun-2015',
       'Apr-2013', 'Sep-2000', 'Jun-1979', 'Dec-1989', 'Oct-1997',
       'Aug-2000', 'Aug-1987', 'Jul-1991', 'Apr-1988', 'Oct-2014',
       'Jul-2002', 'Sep-2009', 'May-2010', 'Sep-1985', 'Feb-1991',
       'Nov-2003', 'Mar-2010', 'Jul-1995', 'Oct-1994', 'Jul-1987',
       'Oct-2009', 'Jan-1997', 'Oct-1993', 'Aug-1992', 'Sep-2005',
       'Jan-2001', 'Jul-1983', 'Jul-2003', 'Nov-2000', 'Jun-1998',
       'Aug-2013', 'Apr-2009', 'Jul-2004', 'Nov-2005', 'Apr-1998',
       'Nov-1993', 'Oct-1991', 'Jun-2004', 'Jun-2008', 'Jan-1993',
       'Mar-2003', 'Mar-2011', 'Jun-2000', 'Mar-2004', 'Feb-2008',
       'May-1973', 'May-2008', 'Jan-2003', 'Mar-2002', 'Aug-1997',
       'Feb-2009', 'Feb-2004', 'Apr-1993', 'Dec-1995', 'Dec-2008',
       'Jan-1990', 'Mar-2012', 'Mar-1987', 'Jun-2011', 'Feb-2011',
       'Jan-2015', 'Jun-2005', 'Mar-2001', 'Jun-1999', 'Mar-1979',
       'Jan-1998', 'May-2000', 'Dec-2001', 'May-2002', 'Oct-2002',
       'Sep-2001', 'Jun-1981', 'May-1994', 'Mar-2015', 'Jan-1994',
       'Jul-2015', 'Sep-2007', 'Aug-2012', 'Feb-1989', 'Jun-2012',
       'Aug-1972', 'Nov-2011', 'Feb-2015', 'Oct-1992', 'Apr-1994',
       'Feb-1985', 'May-2001', 'Jul-2008', 'Dec-1996', 'Jan-1987',
       'May-1995', 'Mar-1996', 'Nov-2009', 'Jul-1998', 'Jan-1988',
       'Jun-1988', 'Apr-1984', 'May-1991', 'Dec-2014', 'Nov-1996',
       'Apr-1978', 'Jul-2009', 'Jun-1970', 'Jun-1990', 'Mar-2008',
       'Jul-2001', 'Oct-1995', 'May-2006', 'Feb-2002', 'Jan-2007',
       'Jul-2006', 'Jul-2000', 'Mar-1990', 'Dec-2012', 'Jun-2014',
       'Jul-2012', 'Jun-1994', 'Feb-2000', 'Nov-1988', 'Oct-1987',
       'Nov-1991', 'Feb-1982', 'Apr-1991', 'Sep-2004', 'Nov-1998',
       'Nov-1983', 'Nov-1994', 'Dec-1972', 'Nov-1995', 'Nov-1992',
       'May-2014', 'May-1997', 'Jun-1989', 'Oct-2015', 'Apr-1986',
       'May-1993', 'Mar-1994', 'Jan-1999', 'Oct-1998', 'Jun-2013',
       'Mar-1995', 'Feb-2012', 'Sep-1993', 'Sep-1989', 'Feb-1993',
       'Jun-1982', 'Aug-1995', 'Nov-2012', 'Aug-1986', 'Dec-2011',
       'Oct-2013', 'May-2011', 'Jan-1980', 'Mar-1988', 'Aug-1985',
       'May-1996', 'Nov-1978', 'Dec-2013', 'May-1985', 'Nov-1982',
       'Mar-2013', 'Jun-1986', 'Jun-1992', 'Oct-1985', 'May-2012',
       'May-1987', 'Dec-2010', 'Nov-2008', 'May-1984', 'Nov-2010',
       'Jun-1993', 'Dec-1993', 'Feb-1990', 'Apr-2008', 'Sep-1995',
       'Jun-2010', 'Jul-2011', 'Feb-1994', 'Jun-2002', 'Jul-1993',
       'Dec-1992', 'Oct-1986', 'Aug-1984', 'Sep-2013', 'May-1982',
       'Mar-1997', 'Jul-1989', 'Apr-1990', 'Jul-1985', 'Aug-2014',
       'Dec-1982', 'Feb-2010', 'Oct-2012', 'May-1986', 'Jul-1994',
       'Aug-1994', 'Jul-1988', 'Apr-1985', 'Feb-2013', 'Mar-1989',
       'Apr-1997', 'Dec-1987', 'Jul-1979', 'Dec-1999', 'May-1988',
       'Dec-1986', 'Jun-2001', 'May-1999', 'Jun-1996', 'Mar-1983',
       'Aug-2015', 'Feb-1987', 'Feb-1983', 'Nov-1989', 'Apr-1992',
       'Jul-1981', 'Feb-1981', 'Jan-2010', 'May-1989', 'Sep-1978',
       'Aug-1975', 'Jun-1997', 'Apr-1983', 'Aug-1988', 'Dec-1984',
       'Aug-1991', 'May-2013', 'Jan-1979', 'Jan-1985', 'Aug-1978',
       'Dec-1978', 'Nov-1970', 'Apr-1987', 'Sep-1986', 'Apr-1996',
       'May-1977', 'Oct-1989', 'Aug-1982', 'Sep-1981', 'May-1983',
       'Jul-1984', 'Sep-2015', 'Nov-1981', 'Jan-2013', 'Sep-1982',
       'Oct-1977', 'Feb-1979', 'Nov-1979', 'Oct-1984', 'Feb-1977',
       'Jul-1978', 'Dec-1981', 'Sep-2014', 'Sep-1972', 'Jul-1971',
       'Nov-1977', 'Nov-1965', 'Mar-1978', 'Jan-1982', 'Mar-1992',
       'Sep-1973', 'Mar-1984', 'Dec-1977', 'Sep-1980', 'Oct-1990',
       'Mar-1981', 'Dec-1985', 'Oct-1982', 'Nov-1985', 'Oct-1974',
       'Sep-1992', 'Feb-1995', 'Nov-1990', 'Apr-1980', 'Apr-2015',
       'Jan-1975', 'May-1974', 'Sep-1990', 'May-1990', 'Nov-1987',
       'Jun-1976', 'Oct-1983', 'Aug-1980', 'Jan-1986', 'Feb-1973',
       'Feb-1986', 'Apr-1976', 'Dec-1971', 'Jan-1992', 'Feb-1971',
       'Jun-1985', 'Feb-1976', 'Jan-1970', 'Oct-1975', 'Apr-1979',
       'Jun-1983', 'Sep-1987', 'Oct-1980', 'Feb-1978', 'Jul-1980',
       'May-1992', 'Jan-1984', 'Oct-1978', 'Mar-1985', 'May-1969',
       'Nov-1980', 'Mar-1975', 'Dec-1980', 'Aug-1976', 'Jul-1977',
       'Nov-1968', 'Sep-1983', 'Jun-1984', 'Nov-1976', 'Mar-1976',
       'Apr-2010', 'Feb-1984', 'May-1976', 'Mar-1970', 'Mar-1977',
       'Feb-1988', 'Dec-1979', 'Feb-1992', 'Oct-1981', 'Apr-1982',
       'Jan-1989', 'May-1978', 'Oct-1969', 'Apr-1962', 'May-1961',
       'Aug-1977', 'Apr-1981', 'Dec-1983', 'Nov-1975', 'Apr-1977',
       'Jul-1976', 'Jul-1982', 'Nov-2015', 'Oct-1976', 'Jul-1967',
       'Jun-1972', 'Mar-1986', 'Jun-1967', 'May-1979', 'Mar-1980',
       'Aug-1971', 'May-1981', 'Jan-1983', 'Sep-1979', 'Jan-1977',
       'Mar-1982', 'Jun-1977', 'Jan-1981', 'Jan-1978', 'Jan-1973',
       'Mar-1971', 'May-1964', 'Feb-1980', 'Jul-1974', 'May-1965',
       'Jul-1973', 'Aug-1973', 'Aug-1981', 'Sep-1971', 'Jun-1978',
       'Jan-1974', 'Aug-1974', 'Jan-1967', 'Apr-1975', 'Sep-1970',
       'Jun-1965', 'Mar-1973', 'Sep-1976', 'Apr-1971', 'Nov-1974',
       'Dec-1968', 'Dec-1976', 'Feb-1966', 'May-1980', 'Aug-1979',
       'Apr-1963', 'Oct-1970', 'Jan-1976', 'Sep-1977', 'Sep-1974',
       'Jan-1954', 'Apr-1973', 'Jan-1969', 'Jun-1980', 'Aug-1983',
       'Jan-1968', 'Aug-1969', 'Dec-1975', 'Jul-1975', 'Jan-1971',
       'Jul-1968', 'Nov-1973', 'Jan-1950', 'Apr-1972', 'Jun-1974',
       'Jul-1950', 'Apr-1968', 'Jan-1963', 'Nov-1966', 'Oct-1972',
       'Dec-1967', 'Aug-1966', 'Mar-1972', 'May-1972', 'Sep-1964',
       'Feb-1972', 'Dec-1973', 'Jan-1958', 'Oct-1973', 'Feb-1963',
       'Aug-1967', 'Oct-1965', 'Feb-1970', 'Oct-1979', 'Jan-1972',
       'Feb-1974', 'Feb-1969', 'Apr-1964', 'Sep-1975', 'Aug-1970',
       'Jul-1965', 'Dec-1970', 'May-1971', 'Apr-1965', 'Jan-1956',
       'Apr-1970', 'Sep-1965', 'Mar-1965', 'Dec-1974', 'Dec-1966',
       'Jan-1965', 'Jan-1960', 'Nov-1959', 'May-1968', 'Jun-1975',
       'Jun-1969', 'Jan-1962', 'May-1970', 'Apr-1974', 'Feb-1967',
       'Aug-1968', 'Sep-1969', 'Apr-1969', 'Mar-1962', 'Jun-1973',
       'Oct-1961', 'Apr-1967', 'Oct-1964', 'Jan-1959', 'Dec-1969',
       'Jun-1964', 'Mar-1968', 'Mar-1969', 'Sep-1967', 'Mar-1967',
       'Jul-1969', 'May-1967', 'Nov-1971', 'Nov-1972', 'Jan-1961',
       'Feb-1962', 'Jun-1968', 'Feb-1975', 'Jul-1966', 'Dec-1964',
       'Sep-1966', 'Sep-1963', 'Aug-1962', 'Jan-1966', 'Oct-1968',
       'Nov-1964', 'Mar-1954', 'Aug-1963', 'Nov-1967', 'Jan-1964',
       'Jul-1964', 'Sep-1968', 'Jun-1971', 'Oct-1971', 'Dec-1965',
       'Oct-1966', 'Jul-1972', 'Feb-1965', 'Jun-1966', 'Aug-1964',
       'Jul-1970', 'Apr-1966', 'May-1966', 'Sep-1962', 'Oct-1967',
       'Apr-1960', 'Jun-1963', 'Nov-1969', 'Dec-1962', 'Feb-1968',
       'Jan-1951', 'Mar-1966', 'Jun-1962', 'Dec-1963', 'Aug-1965',
       'Jan-1957', 'Dec-1961', 'Jul-1961', 'Dec-1947', 'Apr-1957',
       'Mar-1964', 'Mar-1959', 'Jan-1955', 'Jun-1958', 'Feb-1964',
       'Apr-1959', 'Nov-1963', 'Aug-1959', 'May-1963', 'Nov-1961',
       'Jun-1960', 'Mar-1963', 'Jul-1960', 'Oct-1963', 'Dec-1960',
       'Sep-1961', 'Jun-1961', 'Aug-1958', 'Apr-1955', 'May-1960',
       'Oct-1962', 'Dec-1959', 'Jun-1956', 'Feb-1961', 'Jul-1963',
       'Feb-1958', 'Jun-1959', 'Jan-1953', 'Jul-1962', 'Aug-1941',
       'Mar-1961', 'Dec-1946', 'Aug-1961', 'May-1962', 'Feb-1960',
       'Mar-1933', 'Nov-1957', 'Jun-1952', 'Jun-1957', 'May-1958',
       'Nov-1962', 'Aug-1960', 'Mar-1955', 'May-1959', 'Feb-1945',
       'Jan-1948', 'Jul-1959', 'Nov-1960', 'Mar-1957', 'Jul-1952',
       'Jan-1952', 'Apr-1958', 'Jul-1951', 'Apr-1961', 'Dec-1958',
       'Oct-1958', 'Feb-1959', 'Oct-1959', 'Jun-1955', 'Sep-1953',
       'Nov-1956', 'Mar-1958', 'May-1955', 'Mar-1960', 'Aug-1951',
       'Sep-1959', 'Nov-1958', 'Sep-1956', 'May-1957', 'Dec-1956',
       'Jul-1958', 'Sep-1960', 'Oct-1960', 'Aug-1950', 'Aug-1955',
       'Jan-1944', 'Nov-1952', 'Aug-1953', 'Apr-1934', 'Sep-1951',
       'Feb-1934', 'Aug-1957', 'Oct-1957', 'Nov-1953', 'Jul-1955',
       'May-1953', 'Nov-1950', 'Nov-1955', 'Feb-1957', 'Dec-1951',
       'Aug-1946', 'Nov-1954', 'Sep-1957', 'Jun-1949', 'Oct-1950',
       'May-1950', 'Oct-1954', 'Jan-1946', 'Dec-1950', nan], dtype=object)

In [12]:
loan_data["earliest_cr_date"] = pd.to_datetime(loan_data["earliest_cr_line"], format='%b-%Y')

In [13]:
loan_data["earliest_cr_date"].unique()

<DatetimeArray>
['2001-04-01 00:00:00', '1987-06-01 00:00:00', '2011-04-01 00:00:00',
 '2006-02-01 00:00:00', '2000-12-01 00:00:00', '2002-09-01 00:00:00',
 '2004-11-01 00:00:00', '1997-11-01 00:00:00', '1998-08-01 00:00:00',
 '2002-04-01 00:00:00',
 ...
 '1946-08-01 00:00:00', '1954-11-01 00:00:00', '1957-09-01 00:00:00',
 '1949-06-01 00:00:00', '1950-10-01 00:00:00', '1950-05-01 00:00:00',
 '1954-10-01 00:00:00', '1946-01-01 00:00:00', '1950-12-01 00:00:00',
                 'NaT']
Length: 755, dtype: datetime64[ns]

In [14]:
loan_data.dropna(subset=['earliest_cr_date'], inplace=True)

In [15]:
loan_data['ref_date'] = pd.to_datetime('2017-12-01')

In [16]:
loan_data['mths_since_earliest_cr_line'] = (loan_data['ref_date'].dt.to_period('M') - loan_data['earliest_cr_date'].dt.to_period('M')).apply(lambda x: x.n)

In [17]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [18]:
loan_data['mths_since_earliest_cr_line'].describe()

count   2260639.00000
mean        215.68910
std          94.16722
min          25.00000
25%         151.00000
50%         200.00000
75%         265.00000
max        1017.00000
Name: mths_since_earliest_cr_line, dtype: float64

In [19]:
loan_data.loc[loan_data['mths_since_earliest_cr_line'] < 0, 'mths_since_earliest_cr_line'] = loan_data['mths_since_earliest_cr_line'].max()

In [20]:
loan_data['mths_since_earliest_cr_line'].describe()

count   2260639.00000
mean        215.68910
std          94.16722
min          25.00000
25%         151.00000
50%         200.00000
75%         265.00000
max        1017.00000
Name: mths_since_earliest_cr_line, dtype: float64

In [21]:
loan_data['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [22]:
loan_data['term_int'] = loan_data['term'].str.replace(' months', '').str.strip()

In [23]:
loan_data['term_int'].unique()

array(['36', '60'], dtype=object)

In [24]:
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format='%b-%Y')

In [25]:
loan_data['issue_d_date']

0         2018-12-01
1         2018-12-01
2         2018-12-01
3         2018-12-01
4         2018-12-01
             ...
2260663   2017-10-01
2260664   2017-10-01
2260665   2017-10-01
2260666   2017-10-01
2260667   2017-10-01
Name: issue_d_date, Length: 2260639, dtype: datetime64[ns]

In [26]:
loan_data['mths_since_issue_d'] = (loan_data['ref_date'].dt.to_period('M') - loan_data['issue_d_date'].dt.to_period('M')).apply(lambda x: x.n)

In [27]:
loan_data['issue_d_date'].unique()

<DatetimeArray>
['2018-12-01 00:00:00', '2018-11-01 00:00:00', '2018-10-01 00:00:00',
 '2018-09-01 00:00:00', '2018-08-01 00:00:00', '2018-07-01 00:00:00',
 '2018-06-01 00:00:00', '2018-05-01 00:00:00', '2018-04-01 00:00:00',
 '2018-03-01 00:00:00',
 ...
 '2007-12-01 00:00:00', '2007-11-01 00:00:00', '2007-10-01 00:00:00',
 '2007-09-01 00:00:00', '2007-08-01 00:00:00', '2007-07-01 00:00:00',
 '2007-06-01 00:00:00', '2017-12-01 00:00:00', '2017-11-01 00:00:00',
 '2017-10-01 00:00:00']
Length: 139, dtype: datetime64[ns]

In [28]:
loan_data.drop(loan_data[loan_data['issue_d_date'] > '2017-12-01'].index, inplace=True)

In [29]:
loan_data['mths_since_earliest_cr_line'].describe()

count   1765397.00000
mean        223.82233
std          92.32466
min          37.00000
25%         160.00000
50%         207.00000
75%         271.00000
max        1017.00000
Name: mths_since_earliest_cr_line, dtype: float64

In [30]:
loan_data_dummies = [
    pd.get_dummies(loan_data['grade'], prefix='grade', prefix_sep=':'),
    pd.get_dummies(loan_data['sub_grade'], prefix='sub_grade', prefix_sep=':'),
    pd.get_dummies(loan_data['home_ownership'], prefix='home_ownership', prefix_sep=':'),
    pd.get_dummies(loan_data['verification_status'], prefix='verification_status', prefix_sep=':'),
    pd.get_dummies(loan_data['loan_status'], prefix='loan_status', prefix_sep=':'),
    pd.get_dummies(loan_data['purpose'], prefix='purpose', prefix_sep=':'),
    pd.get_dummies(loan_data['addr_state'], prefix='addr_state', prefix_sep=':'),
    pd.get_dummies(loan_data['initial_list_status'], prefix='initial_list_status', prefix_sep=':'),
]

In [31]:
loan_data_dummies = pd.concat(loan_data_dummies, axis=1)

In [32]:
loan_data = pd.concat([loan_data, loan_data_dummies], axis=1)

In [33]:
loan_data

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,emp_length_int,earliest_cr_date,ref_date,mths_since_earliest_cr_line,term_int,issue_d_date,mths_since_issue_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:ND,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w
495242,NaN,NaN,8000,8000,8000.00000,36 months,12.79000,268.75000,C,C1,lead mold maker,4 years,MORTGAGE,95000.00000,Verified,Sep-2016,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,600xx,IL,10.30000,0.00000,May-1993,1.00000,77.00000,79.00000,12.00000,1.00000,11343,47.90000,30.00000,w,2063.66000,2063.66000,7521.68000,7521.68000,5936.34000,1585.34000,0.00000,0.00000,0.00000,Feb-2019,268.75000,Mar-2019,Feb-2019,0.00000,NaN,1,Individual,NaN,NaN,NaN,0.00000,0.00000,30705.00000,2.00000,2.00000,2.00000,2.00000,2.00000,19362.00000,95.00000,5.00000,6.00000,3463.00000,70.00000,23700.00000,5.00000,5.00000,17.00000,8.00000,2559.00000,6558.00000,56.30000,0.00000,0.00000,120.00000,280.00000,6.00000,2.00000,3.00000,6.00000,NaN,1.00000,NaN,0.00000,3.00000,8.00000,4.00000,6.00000,8.00000,10.00000,19.00000,8.00000,12.00000,0.00000,0.00000,0.00000,7.00000,96.40000,75.00000,1.00000,0.00000,44176.00000,30705.00000,15000.00000,20476.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,4.00000,1993-05-01,2017-12-01,295,36,2016-09-01,15,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
495243,NaN,NaN,20000,20000,20000.00000,60 months,17.99000,507.76000,D,D2,Compliance Manager,1 year,MORTGAGE,66000.00000,Not Verified,Sep-2016,Charged Off,n,NaN,NaN,medical,Medical expenses,786xx,TX,12.62000,2.00000,Dec-2008,0.00000,17.00000,117.00000,18.00000,1.00000,3565,31.00000,25.00000,w,0.00000,0.00000,7366.25000,7366.25000,2711.49000,3341.65000,0.00000,1313.11000,236.35980,Oct-2017,507.76000,NaN,Jul-2018,0.00000,45.00000,1,Individual,NaN,NaN,NaN,0.00000,3841.00000,235368.00000,1.00000,11.00000,1.00000,2.00000,1.00000,26700.00000,101.00000,1.00000,1.00000,848.00000,80.00000,11500.00000,1.00000,4.00000,2.00000,3.00000,13076.00000,4891.00000,28.10000,0.00000,0.00000,91.00000,93.00000,12.00000,1.00000,1.00000,12.00000,NaN,12.00000,NaN,0.00000,4.00000,6.00000,4.00000,4.00000,16.00000,6.00000,8.00000,6.00000,18.00000,0.00000,0.00000,0.00000,2.00000,88.00000,25.00000,1.00000,0.00000,254093.00000,30265.00000,6800.00000,26578.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,2008-12-01,2017-12-01,108,60,2016-09-01,15,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True
495244,NaN,NaN,10000,10000,10000.00000,36 months,8.59000,316.10000,A,A5,Supervisory Agent,10+ years,MORTGAGE,137500.00000,Source Verified,Sep-2016,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,330xx,FL,13.42000,0.00000,May-2002,1.00000,NaN,107.00000,18.00000,1.00000,9031,8.80000,37.00000,w,0.00000,0.00000,10962.47908,10962.48000,10000.00000,962.48000,0.00000,0.00000,0.00000,Dec-2018,35.67000,NaN,Dec-2018,0.00000,NaN,1,Individual,NaN,NaN,NaN,0.00000,0.00000,549316.00000,0.00000,2.00000,2.00000,3.00000,9.00000,46469.00000,80.00000,0.00000,2.00000,8713.00000,18.00000,102800.00000,4.00000,3.00000,3.00000,7.00000,34332.00000,68269.00000,11.70000,0.00000,0.00000,143.00000,172.00000,17.00000,7.00000,2.00000,68.00000,NaN,2.00000,NaN,0.00000,2.00000,2.00000,9.00000,15.00000,9.00000,14.00000,26.00000,2.00000,18.00000,0.00000,0.00000,0.00000,3.00000,100.00000,0.00000,1.00000,0.00000,682041.00000,55500.00000,77300.00000,72241.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.00000,2002-05-01,2017-12-01,187,36,2016-09-01,15,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
495245,NaN,NaN,32200,32200,32200.00000,60 months,21.49000,880.02000,D,D5,warehouse/supervisor,10+ years,MORTGAGE,65000.00000,Not Verified,Sep-2016,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,923xx,CA,11.71000,0.00000,Nov-1992,1.00000,NaN,87.00000,17.00000,1.00000,11987,48.10000,34.00000,w,0.00000,0.00000,35770.81275,35770.81000,32200.00000,3570.81000,0.00000,0.00000,0.00000,Apr-2017,31447.60000,NaN,Feb-2019,0.00000,NaN,1,Individual,NaN,NaN,NaN,0.00000,0.00000,173513.00000,1.00000,2.00000,0.00000,3.00000,13.00000,12947.00000,82.00000,2.00000,2.00000,6087.00000,61.00000,24900.00000,7.00000,0.00000,5.00000,5.00000,10845.00000,2666.00000,80.80000,0.00000,0.00000,128.00000,286.00000,3.00000,3.00000,3.00000,32.00000,NaN,0.00000,NaN,0.00000,3.00000,5.00000,5.00000,10.00000,7.00000,14.00000,24.00000,5.00000,17.00000,0.00000,0.00000,0.00000,2.00000,100.00000,40.00000,1.00000,0.00000,199969.00000,24934.00000,13900.00000,15886.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.00000,1992-11-01,2017-12-01,301,60,2016-09-01,15,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
495246,NaN,NaN,2600,2600,2600.00000,36 months,8.99000,82.67000,B,B1,Loaner Coordinator,3 years,RENT,35000.00000,Source Verified,Sep-2016,Fully Paid,n,NaN,NaN,moving,Moving and relocation,970xx,OR,6.73000,0.00000,Sep-2009,0.00000,NaN,NaN,14.00000,0.00000,720,1.40000,24.00000,w,0.00000,0.00000,2662.59024,2662.59000,2600.00000,62.59000,0.00000,0.00000,0.00000,Jan-2017,2492.06000,NaN,Dec-2018,0.00000,NaN,1,Individual,NaN,NaN,NaN,0.00000,0.00000,19497.00000,0.00000,7.00000,0.00000,1.00000,13.00000,18777.00000,92.00000,0.00000,2.00000,383.00000,27.00000,52700.00000,1.00000,0.00000,1.00000,3.00000,1393.00000,49677.00000,1.00000,0.00000,0.00000,84.00000,61.00000,13.00000,13.00000,0.00000,24.00000,NaN,1.00000,NaN,0.00000,4.00000,5.00000,6.00000,8.00000,14.00000,7.00000,10.00000,5.00000,14.00000,0.00000,0.00000,0.00000,0.00000,100.00000,0.00000,0.00000,0.00000,73227.00000,19497.00000,50200.00000,20527.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,3.00000,2009-09-01,2017-12-01,99,36,2016-09-01,15,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260663,NaN,NaN,12000,12000,12000.00000,60 months,14.08000,279.72000,C,C3,house keeper,10+ years,MORTGAGE,58000.00000,Not Verified,Oct-2017,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,054xx,VT,20.88000,0.00000,Jan-2004,0.00000,NaN,NaN,12.00000,0.00000,9592,39.20000,34.00000,w,8687.20000,8687.20000,5360.96000,5360.96000,3312.80000,2048.16000,0.00000,0.00000,0.00000,Feb-2019,279.72000,Mar-2019,Feb-2019,0.00000,NaN,1,Individual,NaN,NaN,NaN,0.00000,7921.00000,45212.00000,2.00000,2.00000,0.00000,1.00000,24.00000,35620.00000,36.00000,3.00000,4.00000,4052.00000,38.00000,24500.00000,2.00000,2.00000,1.00000,5.00000,4110.00000,1807.00000,70.90000,0.00000,0.00000,157.00000,164.00000,1.00000,1.00000,2.00000,9.00000,NaN,9.00000,NaN,0.00000,2.00000,4.00000,3.00000,9.00000,11.00000,10.00000,21.00000,4.00000,12.00000,0.00000,0.00000,0.00000,3.00000,100.00000,66.70000,0.00000,0.00000,73948.00000,45212.00000,6200.00000,49448.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.00000,2004-01-01,2017-12-01,167,60,2017-10-01,2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True
2260664,NaN,NaN,12000,12000,12000.00000,60 months,25.82000,358.01000,E,E4,Skilled Labor,< 1 year,MORTGAGE,30000.00000,Not Verified,Oct-2017,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,971xx,OR,19.28000,3.00000,Mar-2003,1.00000,13.00000,NaN,10.00000,0.00000,3497,20.20000,26.00000,w,0.00000,0.00000,14499.80217,14499.80000,12000.00000,2499.80000,0.00000,0.00000,0.00000,Aug-2018,182.74000,NaN,Sep-2017,0.00000,46.00000,1,Joint App,135000.00000,7.36000,Not Verified,0.00000,550.00000,346404.00000,0.00000,1.00000,1.00000,1.00000,8.00000,9431.00000,78.00000,0.00000,3.00000,2238.00000,44.00000,17300.00000,5.00000,1.00000,7.00000,4.00000,34640.00000,9162.00000,19.60000,0.00000,0.00000,163.00000,174.00000,16.00000,8.00000,4.00000,141.00000,46.00000,0.00000,17.00000,2.00000,1.00000,4.00000,2.00000,5.00000,4.00000,7.00000,18.00000,4.00000,10.00000,0.00000,0.00000,0.00000,1.00000,76.90000,50.00000,0.00000,0.00000,382275.00000,12928.00000,11400.00000,12125.00000,13710.00000,Apr-2003,1.00000,4.00000,11.00000,71.60000,1.00000,17.00000,0.00000,0.00000,7.00000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,2003-03-01,2017-12-01,177,60,2017-10-01,2,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [34]:
loan_data['emp_length_int'].isnull().sum()

np.int64(104920)

In [35]:
fillna_dict = {
    'mths_since_earliest_cr_line': 0,
    'acc_now_delinq': 0,
    'total_acc': 0,
    'pub_rec': 0,
    'open_acc': 0,
    'inq_last_6mths': 0,
    'delinq_2yrs': 0,
    'emp_length_int': 0,
}

loan_data.fillna(value=fillna_dict)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,emp_length_int,earliest_cr_date,ref_date,mths_since_earliest_cr_line,term_int,issue_d_date,mths_since_issue_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:ND,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w
495242,NaN,NaN,8000,8000,8000.00000,36 months,12.79000,268.75000,C,C1,lead mold maker,4 years,MORTGAGE,95000.00000,Verified,Sep-2016,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,600xx,IL,10.30000,0.00000,May-1993,1.00000,77.00000,79.00000,12.00000,1.00000,11343,47.90000,30.00000,w,2063.66000,2063.66000,7521.68000,7521.68000,5936.34000,1585.34000,0.00000,0.00000,0.00000,Feb-2019,268.75000,Mar-2019,Feb-2019,0.00000,NaN,1,Individual,NaN,NaN,NaN,0.00000,0.00000,30705.00000,2.00000,2.00000,2.00000,2.00000,2.00000,19362.00000,95.00000,5.00000,6.00000,3463.00000,70.00000,23700.00000,5.00000,5.00000,17.00000,8.00000,2559.00000,6558.00000,56.30000,0.00000,0.00000,120.00000,280.00000,6.00000,2.00000,3.00000,6.00000,NaN,1.00000,NaN,0.00000,3.00000,8.00000,4.00000,6.00000,8.00000,10.00000,19.00000,8.00000,12.00000,0.00000,0.00000,0.00000,7.00000,96.40000,75.00000,1.00000,0.00000,44176.00000,30705.00000,15000.00000,20476.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,4.00000,1993-05-01,2017-12-01,295,36,2016-09-01,15,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
495243,NaN,NaN,20000,20000,20000.00000,60 months,17.99000,507.76000,D,D2,Compliance Manager,1 year,MORTGAGE,66000.00000,Not Verified,Sep-2016,Charged Off,n,NaN,NaN,medical,Medical expenses,786xx,TX,12.62000,2.00000,Dec-2008,0.00000,17.00000,117.00000,18.00000,1.00000,3565,31.00000,25.00000,w,0.00000,0.00000,7366.25000,7366.25000,2711.49000,3341.65000,0.00000,1313.11000,236.35980,Oct-2017,507.76000,NaN,Jul-2018,0.00000,45.00000,1,Individual,NaN,NaN,NaN,0.00000,3841.00000,235368.00000,1.00000,11.00000,1.00000,2.00000,1.00000,26700.00000,101.00000,1.00000,1.00000,848.00000,80.00000,11500.00000,1.00000,4.00000,2.00000,3.00000,13076.00000,4891.00000,28.10000,0.00000,0.00000,91.00000,93.00000,12.00000,1.00000,1.00000,12.00000,NaN,12.00000,NaN,0.00000,4.00000,6.00000,4.00000,4.00000,16.00000,6.00000,8.00000,6.00000,18.00000,0.00000,0.00000,0.00000,2.00000,88.00000,25.00000,1.00000,0.00000,254093.00000,30265.00000,6800.00000,26578.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,2008-12-01,2017-12-01,108,60,2016-09-01,15,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True
495244,NaN,NaN,10000,10000,10000.00000,36 months,8.59000,316.10000,A,A5,Supervisory Agent,10+ years,MORTGAGE,137500.00000,Source Verified,Sep-2016,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,330xx,FL,13.42000,0.00000,May-2002,1.00000,NaN,107.00000,18.00000,1.00000,9031,8.80000,37.00000,w,0.00000,0.00000,10962.47908,10962.48000,10000.00000,962.48000,0.00000,0.00000,0.00000,Dec-2018,35.67000,NaN,Dec-2018,0.00000,NaN,1,Individual,NaN,NaN,NaN,0.00000,0.00000,549316.00000,0.00000,2.00000,2.00000,3.00000,9.00000,46469.00000,80.00000,0.00000,2.00000,8713.00000,18.00000,102800.00000,4.00000,3.00000,3.00000,7.00000,34332.00000,68269.00000,11.70000,0.00000,0.00000,143.00000,172.00000,17.00000,7.00000,2.00000,68.00000,NaN,2.00000,NaN,0.00000,2.00000,2.00000,9.00000,15.00000,9.00000,14.00000,26.00000,2.00000,18.00000,0.00000,0.00000,0.00000,3.00000,100.00000,0.00000,1.00000,0.00000,682041.00000,55500.00000,77300.00000,72241.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.00000,2002-05-01,2017-12-01,187,36,2016-09-01,15,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
495245,NaN,NaN,32200,32200,32200.00000,60 months,21.49000,880.02000,D,D5,warehouse/supervisor,10+ years,MORTGAGE,65000.00000,Not Verified,Sep-2016,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,923xx,CA,11.71000,0.00000,Nov-1992,1.00000,NaN,87.00000,17.00000,1.00000,11987,48.10000,34.00000,w,0.00000,0.00000,35770.81275,35770.81000,32200.00000,3570.81000,0.00000,0.00000,0.00000,Apr-2017,31447.60000,NaN,Feb-2019,0.00000,NaN,1,Individual,NaN,NaN,NaN,0.00000,0.00000,173513.00000,1.00000,2.00000,0.00000,3.00000,13.00000,12947.00000,82.00000,2.00000,2.00000,6087.00000,61.00000,24900.00000,7.00000,0.00000,5.00000,5.00000,10845.00000,2666.00000,80.80000,0.00000,0.00000,128.00000,286.00000,3.00000,3.00000,3.00000,32.00000,NaN,0.00000,NaN,0.00000,3.00000,5.00000,5.00000,10.00000,7.00000,14.00000,24.00000,5.00000,17.00000,0.00000,0.00000,0.00000,2.00000,100.00000,40.00000,1.00000,0.00000,199969.00000,24934.00000,13900.00000,15886.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.00000,1992-11-01,2017-12-01,301,60,2016-09-01,15,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
495246,NaN,NaN,2600,2600,2600.00000,36 months,8.99000,82.67000,B,B1,Loaner Coordinator,3 years,RENT,35000.00000,Source Verified,Sep-2016,Fully Paid,n,NaN,NaN,moving,Moving and relocation,970xx,OR,6.73000,0.00000,Sep-2009,0.00000,NaN,NaN,14.00000,0.00000,720,1.40000,24.00000,w,0.00000,0.00000,2662.59024,2662.59000,2600.00000,62.59000,0.00000,0.00000,0.00000,Jan-2017,2492.06000,NaN,Dec-2018,0.00000,NaN,1,Individual,NaN,NaN,NaN,0.00000,0.00000,19497.00000,0.00000,7.00000,0.00000,1.00000,13.00000,18777.00000,92.00000,0.00000,2.00000,383.00000,27.00000,52700.00000,1.00000,0.00000,1.00000,3.00000,1393.00000,49677.00000,1.00000,0.00000,0.00000,84.00000,61.00000,13.00000,13.00000,0.00000,24.00000,NaN,1.00000,NaN,0.00000,4.00000,5.00000,6.00000,8.00000,14.00000,7.00000,10.00000,5.00000,14.00000,0.00000,0.00000,0.00000,0.00000,100.00000,0.00000,0.00000,0.00000,73227.00000,19497.00000,50200.00000,20527.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,3.00000,2009-09-01,2017-12-01,99,36,2016-09-01,15,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260663,NaN,NaN,12000,12000,12000.00000,60 months,14.08000,279.72000,C,C3,house keeper,10+ years,MORTGAGE,58000.00000,Not Verified,Oct-2017,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,054xx,VT,20.88000,0.00000,Jan-2004,0.00000,NaN,NaN,12.00000,0.00000,9592,39.20000,34.00000,w,8687.20000,8687.20000,5360.96000,5360.96000,3312.80000,2048.16000,0.00000,0.00000,0.00000,Feb-2019,279.72000,Mar-2019,Feb-2019,0.00000,NaN,1,Individual,NaN,NaN,NaN,0.00000,7921.00000,45212.00000,2.00000,2.00000,0.00000,1.00000,24.00000,35620.00000,36.00000,3.00000,4.00000,4052.00000,38.00000,24500.00000,2.00000,2.00000,1.00000,5.00000,4110.00000,1807.00000,70.90000,0.00000,0.00000,157.00000,164.00000,1.00000,1.00000,2.00000,9.00000,NaN,9.00000,NaN,0.00000,2.00000,4.00000,3.00000,9.00000,11.00000,10.00000,21.00000,4.00000,12.00000,0.00000,0.00000,0.00000,3.00000,100.00000,66.70000,0.00000,0.00000,73948.00000,45212.00000,6200.00000,49448.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.00000,2004-01-01,2017-12-01,167,60,2017-10-01,2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True
2260664,NaN,NaN,12000,12000,12000.00000,60 months,25.82000,358.01000,E,E4,Skilled Labor,< 1 year,MORTGAGE,30000.00000,Not Verified,Oct-2017,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,971xx,OR,19.28000,3.00000,Mar-2003,1.00000,13.00000,NaN,10.00000,0.00000,3497,20.20000,26.00000,w,0.00000,0.00000,14499.80217,14499.80000,12000.00000,2499.80000,0.00000,0.00000,0.00000,Aug-2018,182.74000,NaN,Sep-2017,0.00000,46.00000,1,Joint App,135000.00000,7.36000,Not Verified,0.00000,550.00000,346404.00000,0.00000,1.00000,1.00000,1.00000,8.00000,9431.00000,78.00000,0.00000,3.00000,2238.00000,44.00000,17300.00000,5.00000,1.00000,7.00000,4.00000,34640.00000,9162.00000,19.60000,0.00000,0.00000,163.00000,174.00000,16.00000,8.00000,4.00000,141.00000,46.00000,0.00000,17.00000,2.00000,1.00000,4.00000,2.00000,5.00000,4.00000,7.00000,18.00000,4.00000,10.00000,0.00000,0.00000,0.00000,1.00000,76.90000,50.00000,0.00000,0.00000,382275.00000,12928.00000,11400.00000,12125.00000,13710.00000,Apr-2003,1.00000,4.00000,11.00000,71.60000,1.00000,17.00000,0.00000,0.00000,7.00000,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,2003-03-01,2017-12-01,177,60,2017-10-01,2,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [36]:
loan_data['emp_length_int'].isnull().sum()

np.int64(104920)

In [37]:
loan_data['loan_status'].unique()

array(['Current', 'Charged Off', 'Fully Paid', 'Late (31-120 days)',
       'In Grace Period', 'Late (16-30 days)', 'Default',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

In [38]:
loan_data['loan_status'].value_counts()

loan_status
Fully Paid                                             1001712
Current                                                 482377
Charged Off                                             254713
Late (31-120 days)                                       15388
In Grace Period                                           6051
Late (16-30 days)                                         2414
Does not meet the credit policy. Status:Fully Paid        1962
Does not meet the credit policy. Status:Charged Off        758
Default                                                     22
Name: count, dtype: int64

In [39]:
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off', 'Late (31-120 days)', 'Default']), 0 , 1)

In [40]:
loan_data[['good_bad', 'loan_status']]

         good_bad  loan_status
495242          1      Current
495243          0  Charged Off
495244          1   Fully Paid
495245          1   Fully Paid
495246          1   Fully Paid
...           ...          ...
2260663         1      Current
2260664         1   Fully Paid
2260665         1      Current
2260666         1      Current
2260667         1      Current

[1765397 rows x 2 columns]

SCIKIT LEARN TRAIN DATA SET

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
loan_data_input_train, loan_data_input_test, loan_data_target_train, loan_data_target_test = train_test_split(loan_data.drop('good_bad', axis=1), loan_data['good_bad'], test_size=0.2, random_state=42)

In [43]:
loan_data_input_train.shape

(1412317, 279)

In [44]:
loan_data_input_test.shape

(353080, 279)

In [45]:
loan_data_target_train.shape

(1412317,)

In [46]:
loan_data_target_test.shape

(353080,)

DATA PREPROCESSING

In [47]:
df_input_prepr = loan_data_input_train.copy()

In [48]:
df_target_prepr = loan_data_target_train.copy()

CHECK 1 FEATURE 1ST FOR TESTING

In [49]:
df_target_prepr

750638     1
516492     1
712572     0
2190904    1
1751468    1
          ..
754420     1
1909656    1
627174     1
1166397    1
617200     0
Name: good_bad, Length: 1412317, dtype: int64

In [50]:
df_1 = pd.concat([df_input_prepr['grade'], df_target_prepr], axis=1)

In [51]:
# TO GET THE NUMBER OF GRADE IN THE DATA USE COUNT

df_1.groupby(df_1.columns.values[0], as_index=False)[df_1.columns.values[1]].count()

  grade  good_bad
0     A    237532
1     B    417842
2     C    418897
3     D    204586
4     E     93395
5     F     30816
6     G      9249

In [52]:
# TO GET THE NUMBER OF GRADE % OF GOOD VS BAD USE MEAN SINCE GOOD = 1 BAD = 0, AVERAGE = %

df_1.groupby(df_1.columns.values[0], as_index=False)[df_1.columns.values[1]].mean()

  grade  good_bad
0     A   0.95238
1     B   0.89844
2     C   0.83431
3     D   0.76218
4     E   0.68875
5     F   0.62127
6     G   0.59812

In [53]:
# COMBINE THE DATAFRAME TOGETHER

df_1 = pd.concat([
    df_1.groupby(df_1.columns.values[0], as_index=False)[df_1.columns.values[1]].count(),
    df_1.groupby(df_1.columns.values[0], as_index=False)[df_1.columns.values[1]].mean()
], axis=1)

In [54]:
df_1

  grade  good_bad grade  good_bad
0     A    237532     A   0.95238
1     B    417842     B   0.89844
2     C    418897     C   0.83431
3     D    204586     D   0.76218
4     E     93395     E   0.68875
5     F     30816     F   0.62127
6     G      9249     G   0.59812

In [55]:
df_1 = df_1.iloc[:, [0, 1, 3]]

In [56]:
df_1

  grade  good_bad  good_bad
0     A    237532   0.95238
1     B    417842   0.89844
2     C    418897   0.83431
3     D    204586   0.76218
4     E     93395   0.68875
5     F     30816   0.62127
6     G      9249   0.59812

In [57]:
df_1.columns = [df_1.columns.values[0], 'n_obs', '%_good']

In [58]:
df_1

  grade   n_obs  %_good
0     A  237532 0.95238
1     B  417842 0.89844
2     C  418897 0.83431
3     D  204586 0.76218
4     E   93395 0.68875
5     F   30816 0.62127
6     G    9249 0.59812

In [59]:
# GET THE % OF OBSERVATIONS FOR THAT PARTICULAR GRADE

df_1['%_n_obs'] = df_1['n_obs'] / df_1['n_obs'].sum()

In [60]:
df_1

  grade   n_obs  %_good  %_n_obs
0     A  237532 0.95238  0.16819
1     B  417842 0.89844  0.29586
2     C  418897 0.83431  0.29660
3     D  204586 0.76218  0.14486
4     E   93395 0.68875  0.06613
5     F   30816 0.62127  0.02182
6     G    9249 0.59812  0.00655

In [61]:
# GET THE COUNT OF GOOD AND BAD FOR A PARTICULAR GRADE

df_1['n_good'] = df_1['%_good'] * df_1['n_obs']
df_1['n_bad'] = (1 - df_1['%_good']) * df_1['n_obs']

In [62]:
df_1

  grade   n_obs  %_good  %_n_obs       n_good       n_bad
0     A  237532 0.95238  0.16819 226220.00000 11312.00000
1     B  417842 0.89844  0.29586 375404.00000 42438.00000
2     C  418897 0.83431  0.29660 349492.00000 69405.00000
3     D  204586 0.76218  0.14486 155932.00000 48654.00000
4     E   93395 0.68875  0.06613  64326.00000 29069.00000
5     F   30816 0.62127  0.02182  19145.00000 11671.00000
6     G    9249 0.59812  0.00655   5532.00000  3717.00000

In [63]:
# OUT OF ALL GOOD/BAD, GET THE % FOR THE PARTICULAR GRADE OF GOOD/BAD

df_1['%_n_good'] = df_1['n_good'] / df_1['n_good'].sum()
df_1['%_n_bad'] = df_1['n_bad'] / df_1['n_bad'].sum()

In [64]:
df_1

  grade   n_obs  %_good  %_n_obs       n_good       n_bad  %_n_good  %_n_bad
0     A  237532 0.95238  0.16819 226220.00000 11312.00000   0.18914  0.05231
1     B  417842 0.89844  0.29586 375404.00000 42438.00000   0.31387  0.19623
2     C  418897 0.83431  0.29660 349492.00000 69405.00000   0.29220  0.32092
3     D  204586 0.76218  0.14486 155932.00000 48654.00000   0.13037  0.22497
4     E   93395 0.68875  0.06613  64326.00000 29069.00000   0.05378  0.13441
5     F   30816 0.62127  0.02182  19145.00000 11671.00000   0.01601  0.05397
6     G    9249 0.59812  0.00655   5532.00000  3717.00000   0.00463  0.01719

In [65]:
# GET THE WoE

df_1['WoE'] = np.log(df_1['%_n_good']/df_1['%_n_bad'])

In [66]:
# SORT BY THE WoE THEN RESET THE INDEX, USE DROP = TRUE SINCE IF DONT SET IT, THE OLD INDEX WILL BE ADDED AS A NEW COLUMN

df_1 = df_1.sort_values(['WoE'])
df_1 = df_1.reset_index(drop=True)

In [67]:
df_1

,grade,n_obs,%_good,%_n_obs,n_good,n_bad,%_n_good,%_n_bad,WoE
0,G,9249,0.59812,0.00655,5532.00000,3717.00000,0.00463,0.01719,-1.31264
1,F,30816,0.62127,0.02182,19145.00000,11671.00000,0.01601,0.05397,-1.21534
2,E,93395,0.68875,0.06613,64326.00000,29069.00000,0.05378,0.13441,-0.91598
3,D,204586,0.76218,0.14486,155932.00000,48654.00000,0.13037,0.22497,-0.54559
4,C,418897,0.83431,0.29660,349492.00000,69405.00000,0.29220,0.32092,-0.09375
5,B,417842,0.89844,0.29586,375404.00000,42438.00000,0.31387,0.19623,0.46969
6,A,237532,0.95238,0.16819,226220.00000,11312.00000,0.18914,0.05231,1.28537

In [68]:
# GET INFORMATION VALUE, SUM OF (%_n_good - $_n_bad) * WoE
# IV IS THE SAME FOR ALL OF THE ROWS SINCE IT IS THE INFORMATION VALUE OF THE CATEGORY ITSELF

df_1['IV'] = ((df_1['%_n_good'] - df_1['%_n_bad']) * df_1['WoE']).sum()

In [69]:
df_1

,grade,n_obs,%_good,%_n_obs,n_good,n_bad,%_n_good,%_n_bad,WoE,IV
0,G,9249,0.59812,0.00655,5532.00000,3717.00000,0.00463,0.01719,-1.31264,0.42192
1,F,30816,0.62127,0.02182,19145.00000,11671.00000,0.01601,0.05397,-1.21534,0.42192
2,E,93395,0.68875,0.06613,64326.00000,29069.00000,0.05378,0.13441,-0.91598,0.42192
3,D,204586,0.76218,0.14486,155932.00000,48654.00000,0.13037,0.22497,-0.54559,0.42192
4,C,418897,0.83431,0.29660,349492.00000,69405.00000,0.29220,0.32092,-0.09375,0.42192
5,B,417842,0.89844,0.29586,375404.00000,42438.00000,0.31387,0.19623,0.46969,0.42192
6,A,237532,0.95238,0.16819,226220.00000,11312.00000,0.18914,0.05231,1.28537,0.42192

CREATE A FUNCTION FOR ALL OF THESE CALCULATIONS

In [70]:
def woe_discrete(input_df, variable_name, good_bad_target_df):
    # JOIN INPUT DF OF VARIABLE AND TARGET DF
    df = pd.concat([input_df[variable_name], good_bad_target_df], axis=1)
    # GET THE COUNT AND MEAN OF VARIABLE WITH RESPECT TO TARGET
    df = pd.concat([
    df.groupby(df.columns.values[0], as_index=False)[df.columns.values[1]].count(),
    df.groupby(df.columns.values[0], as_index=False)[df.columns.values[1]].mean()
], axis=1)
    # REMOVE REPEATED COLUMNS
    df = df.iloc[:, [0, 1, 3]]
    # RENAME COLS
    df.columns = [df.columns.values[0], 'n_obs', '%_good']
    # GET % OF OBSERVATION RESPECTIVE TO EACH CATEGORY
    df['%_n_obs'] = df['n_obs'] / df['n_obs'].sum()
    # GET THE COUNT OF GOOD AND BAD FOR A PARTICULAR CATEGORY
    df['n_good'] = df['%_good'] * df['n_obs']
    df['n_bad'] = (1 - df['%_good']) * df['n_obs']
    # OUT OF ALL GOOD/BAD, GET THE % FOR THE PARTICULAR CATEGORY OF GOOD/BAD
    df['%_n_good'] = df['n_good'] / df['n_good'].sum()
    df['%_n_bad'] = df['n_bad'] / df['n_bad'].sum()
    # GET THE WoE
    df['WoE'] = np.log(df['%_n_good']/df['%_n_bad'])
    # SORT BY THE WoE THEN RESET THE INDEX, USE DROP = TRUE SINCE IF DONT SET IT, THE OLD INDEX WILL BE ADDED AS A NEW COLUMN
    df = df.sort_values(['WoE'])
    df = df.reset_index(drop=True)
    # GET INFORMATION VALUE, SUM OF (%_n_good - $_n_bad) * WoE
    # IV IS THE SAME FOR ALL OF THE ROWS SINCE IT IS THE INFORMATION VALUE OF THE CATEGORY ITSELF
    df['IV'] = ((df['%_n_good'] - df['%_n_bad']) * df_1['WoE']).sum()
    return df

In [71]:
df_temp = woe_discrete(df_input_prepr, 'grade', df_target_prepr)
df_temp

,grade,n_obs,%_good,%_n_obs,n_good,n_bad,%_n_good,%_n_bad,WoE,IV
0,G,9249,0.59812,0.00655,5532.00000,3717.00000,0.00463,0.01719,-1.31264,0.42192
1,F,30816,0.62127,0.02182,19145.00000,11671.00000,0.01601,0.05397,-1.21534,0.42192
2,E,93395,0.68875,0.06613,64326.00000,29069.00000,0.05378,0.13441,-0.91598,0.42192
3,D,204586,0.76218,0.14486,155932.00000,48654.00000,0.13037,0.22497,-0.54559,0.42192
4,C,418897,0.83431,0.29660,349492.00000,69405.00000,0.29220,0.32092,-0.09375,0.42192
5,B,417842,0.89844,0.29586,375404.00000,42438.00000,0.31387,0.19623,0.46969,0.42192
6,A,237532,0.95238,0.16819,226220.00000,11312.00000,0.18914,0.05231,1.28537,0.42192

In [73]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()